# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopBotDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopbot.ShopBot')),
            ],
        ),
    ]
